CREATE TABLE USERS(
   USERID INT              NOT NULL AUTO_INCREMENT,
   LASTNAME VARCHAR (225)  NOT NULL,
   FIRSTNAME VARCHAR (225) NOT NULL,
   ADDRESS VARCHAR (225)      NOT NULL,
   NAME VARCHAR (225)      NOT NULL,
);